POST http://localhost:3000/messages
Content-Type: application/json
    {
        "message": " Hello World!",
        "category": "Finance"
    }

POST http://localhost:3000/user
Content-Type: application/json
    {
"name":"johnny Bravo",
"email":"john@abc.com",
"phone":"1234567890",
"suscribed":["Sports","Finance"],
"channels":["SMS"]
}


GET http://localhost:3000/ping